name       : playmymusic
version    : 1.0.1
release    : 1
source     :
    - https://github.com/artemanufrij/playmymusic/archive/1.0.1.tar.gz : 1e7e1dd9df44d46e6148c75636cb76e3944b38d0f8b868a2dee83c832e677355
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : A music player for listening to local music files, online radios, and Audio CD's
description: |
    A music player for listening to local music files, online radios, and Audio CD's
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(sqlite3)
    - pkgconfig(taglib)
    - meson
    - vala
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
