name       : openresolv
version    : 3.9.0
release    : 1
source     :
    - https://roy.marples.name/downloads/openresolv/openresolv-3.9.0.tar.xz : 51a04d39232bb797c9efeaad51a525cf50a1deefcb19a1ea5dd3475118634db8
license    : BSD
component  : network
summary    : resolv.conf management framework (resolvconf)
description: |
    Enter resolvconf, the middleman between the network configuration services and /etc/resolv.conf. resolvconf itself is just a script that stores, removes and lists a full resolv.conf generated for the interface. It then calls all the helper scripts it knows about so it can configure the real /etc/resolv.conf and optionally any local nameservers other than libc.
builddeps  :
    - pkgconfig(systemd)
setip      : |
    %configure
build      : |
    %make
install    : |
    %make_install
