name       : showmypictures
version    : 0.2.5
release    : 1
source     :
    - https://github.com/artemanufrij/showmypictures/archive/0.2.5.tar.gz : 82e463f98bc01c19e06cd3f886c15300cc45fffb1ee82631387c7acf22e41ad9
license    : GPL-2.0
component  : multimedia.graphics
summary    : An image viewer for managing local image files
description: |
    An image viewer for managing local image files
builddeps  :
    - pkgconfig(gexiv2)
    - pkgconfig(granite)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libraw)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.0)
    - vala
setup      : |
    %apply_patches
    mkdir cmake
    install -m 00644 $pkgfiles/cmake/*.cmake cmake/.
    %cmake .
build      : |
    %make
install    : |
    %make_install
