name       : hardcode-tray
version    : 4.2
release    : 1
source     :
    - https://github.com/bil-elmoussaoui/Hardcode-Tray/archive/v4.2.tar.gz : 58e1d246a2ead600ac82cf2d83c22dad1659f0da2be825cf54d779e18a23ccc1
license    :
    - BSD-3-Clause
    - GPL-3.0
component  : desktop.theme
summary    : Fixes Hardcoded tray icons in Linux
description: |
    The script will automatically detect your default theme, the correct icon size, the hard-coded applications, the correct icons for each indicator and fix them. All that with the possibility to revert to the original icons.
rundeps  :
    - imagemagick
    - python3-gobject
    - gobject-introspection
    - librsvg
    - libcairo
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
