name       : audience
version    : 0.2.5
release    : 2
source     :
    - https://github.com/elementary/videos/archive/0.2.5.tar.gz : 4f22565033f5c44380d215c5f9c3672a8a2ad75d81af0e06b7b5a4bf18522207
license    : GPL-3.0
component  : multimedia.video
summary    : Audience videos app designed for elementary OS
description: |
    Audience videos app designed for elementary OS
builddeps  :
    - pkgconfig(clutter-gst-3.0)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(granite)
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install
